### ISSUE TITLE
Consensus redesign to improve multi-threaded performance

### ISSUE THREAD

**Issue by jkitman** [fedimint/minimint#148]
Currently consensus does not scale with available threads and generates empty epochs which wastes resources.  In order to improve performance and simplify the consensus model we can adopt the following pub/sub model:

Create a *proposal queue* which allows multiple threads to submit `ConsensusItem` to be included in the next proposal.
- The API thread will submit new transactions to the queue
- Consensus threads can submit new items as a result of processing a `ConsensusOutcome` (e.g. peg-out sigs, blind sigs)
- Modules may also spawn threads to generate consensus items based on external events (such as the bitcoin block height increasing).
- The proposal queue will filter out all items from past proposals until a consensus thread removes the past proposal, indicating that the outcome of that proposal has been processed.

Any number of *consensus threads* which will consume consensus items to generate a `ConsensusProposal`, run the proposal through HBBFT, and process the outcome.
- Consensus threads are ordered and must generate proposals and process consensus outcomes in round-robin order (otherwise consensus state might become inconsistent between peers)
- Consensus threads generate a proposal if there are any consensus items or if they receive an HBBFT message indicating a proposal has been started by a peer.
- Proposals are guaranteed to be based on outcomes after n epochs, where n is the number of consensus threads (relevant for dropping non-contributing peers).

These changes also suggest that modules should move towards a simpler message-based pattern: receive new txs / outcome items and send consensus items.  This would help decouple the modules from the consensus logic, eventually allowing them to even run remotely.

**Comment by elsirion** [comment]
I think there are a few challenges this proposal doesn't address:
* How do you ensure that e.g. the wallet module makes a contribution if the epoch is triggered by a transaction or hbbft message being received? You may need that contribution to properly process the transaction
* Such a pipeline would require saving target epochs by which we expect signature share contributions to ban non-contributing peers, right now that makes it probably not worth it.

>  This would help decouple the modules from the consensus logic, eventually allowing them to even run remotely.

I don't think that's any priority at all. It would also require modules to be aware of transactions (you propose giving them entire transactions?) leading to cyclic dependencies (the transaction type depends on all modules). To fix this there'd need to be a lot of "dynamic typing" by just passing binary data (similar trade-off in #144). I'm very opposed to that idea since it would destroy many of the guarantees rust gives us.

I think for now keeping the current proposal generation as-is and adding a way to notify the thread doing the generation to do so only when required is much simpler and sufficiently flexible. What that would mean:
* add a `async fn await_wants_to_propose(&self)` to the `Module` trait that blocks until the module has something to propose. In practice that means for the following modules:
  * **Wallet**: Return immediately if there are PSBT signatures to contribute, otherwise block till the block height changes (poll bitcoind).
  * **Mint**: Return immediately if there are signature shares to contribute, block forever otherwise.
  * **LN**: Return immediately if there are decryption shares to contribute, block forever otherwise.
* add a notification channel for submitted transactions (or subscribe to DB changes)
* add a notification channel that signals we received a HBBFT message for an future epoch
* Wait for any of these events (and maybe some timer just in case) and once any fires build a proposal and contribute to consensus as we already do now

**Comment by elsirion** [comment]
Do we want to keep this open for the next few years till we hit performance bottle-necks with the current version or just close for now?

**Comment by jkitman** [comment]
> Do we want to keep this open for the next few years till we hit performance bottle-necks with the current version or just close for now?

Yeah we can close for now and create an issue with a better description later.
