### ISSUE TITLE
Fix bugs with peg-out PSBTs

### ISSUE THREAD

**Issue by jkitman** [fedimint/minimint#196]
I discovered bugs with the peg-out PSBTs right now:
- Get a change tweak key error when signing the PSBT with >1 peg-outs
- If we need to create another PSBT before a change UTXO is confirmed we get a subtraction error (not enough SpendableUTXOs)
- If the peg-in/peg-out fees < the bitcoin fee rate then the balance sheet of the fed can go negative (we spend more in on-chain fees than we charge users.

See failing integration tests here: https://github.com/jkitman/minimint/tree/fix-peg-out-change-bugs

Related to #1

**Comment by jkitman** [comment]
Thoughts on fees:
- The fed should never pay more in tx fees than users have paid
- Users should be able to decrease the peg-out time by paying more fees (as difference between a mint tx's inputs and outputs)
- Fees that the fed keeps (i.e. profits) should be separately defined from on-chain fees

For this we need to modify the wallet API:
- Return min sats/byte to for an immediate transaction broadcast (configured by # of estimated blocks)
- Return min sats/byte to add a new peg-out (configured by minimum sats/byte increase of new peg-out UTXOs)
- All fed transactions must have a change output and perform CPFP on the most recent unconfirmed peg-out tx (so users can bump fees on past peg-outs)

**Comment by elsirion** [comment]
> If we need to create another PSBT before a change UTXO is confirmed we get a subtraction error (not enough SpendableUTXOs)

I see two options: postpone the withdraw or build on unconfirmed tx. The latter sounds like a logistical nightmare so I'd like to avoid it for now. Eventually we'll just have to take care that we ideally always have >1 UTXO.

> The fed should never pay more in on-chain fees than users have paid

Agreed, we could track that in the peg-outs. That will be necessary as soon as we implement dynamic user fees since they might have changed between submitting the peg-out and the federation wanting to publish it. I wonder though how we will account for wallet management by the federation (e.g. splitting/combining its change, something the unlucky user in that tx shouldn't pay for).

> Users should be able to decrease the peg-out urgency by paying more fees (as difference between a fed tx's inputs and outputs)

Interesting idea, there could be two tiers:
1. Instant: for payments
2. Aggregated: for rabalancing (e.g. at least once a day, or whenever there are enough peg-outs)

Although the more I think about it I think we should only offer instant and get rid of a lot of complexity for now. That aggregation was premature optimization. Waiting a long time also exposes us to changes in the fee market and when we submit the tx the fee we can afford could be insufficient.

> All fed transactions must have a change output and perform CPFP on the most recent unconfirmed peg-out tx (so users can bump fees on past peg-outs)

Where would the money for CPFP come from? The next user that wants to peg-out?

**Comment by jkitman** [comment]
@elsirion As usual, after thinking about it more I agree with you that aggregated transactions is too complicated to implement properly right now and would only make sense once there is a lot of peg-out volume.  Here are my updated thoughts, I'll take a stab at implementing the Separate RBF functionality for now:

**Requirements of any peg-out scheme**
- Mint never pays more fees than users contribute (would result in negative balance)
- Handle waiting for change (rather than failing if there are not enough confirmed UTXOs)
- Have a mechanism for increasing fees (to avoid stuck transactions)

**Separate RBF (Most user control, but peg-outs might get stuck in a queue)**
- Peg-outs use separate input UTXOs and allow users to RBF their peg-outs independently
- If not enough UTXOs are available then peg-out requests are queued
- Higher min peg-out fees are required to ensure change becomes available in a reasonable time

**Shared RBF (Most fee efficient, but more complicated)**
- Every new peg-out bumps the fee of a shared unconfirmed transaction by a min sat/byte
- Users who contribute peg-outs later may need to pay more fees due to more inputs/outputs
- Every transaction must use the previous transaction’s change as input (to ensure there is only one valid tx per peg-out)
- To handle reorgs peg-outs must be tracked and recomputed until finality is reached (10 blocks)

**Comment by elsirion** [comment]
> Have a mechanism for increasing fees (to avoid stuck transactions)

I think that's optional for now, we should just be very conservative with our fee estimations.

We generally have the problem that we'll think a tx is unconfirmed till it's covered 10 blocks deep (the alternative is implementing enormously annoying and error-prone logic for the time in between to agree on if a tx is confirmed, which might change over time). That means e.g. Separate RBF might fail if done for a confirmed tx and then we have to track all possible change outputs because we can't know which one will be confirmed for us in the end.

Shared RBF has the further problem that it might upset users that relied on the initial tx id. The common wisom seems to be that user-facing things should rather use CPFP. Separate RBF may be a good middle ground though since it only affects the user who initiates it.

I feel we can mostly leave it to users for now. With high enough estimates it won't be a problem often and most of the on-chain tx will probably come from the LN gateway, they can CPFP as needed. Not having some liquidity buffer to handle such situations is really annoying.

**Comment by jkitman** [comment]
Replaced by #233.
