### ISSUE TITLE
question: is integration with omnibolt tether on the roadmap 

### ISSUE THREAD

**Issue by earonesty** [fedimint/minimint#282]
while custody is a problem that fedimint solves, it would be amazing if fedimint supported onboarding as well

 - integration with venmo/paypal to easily pay and buy bitcoin from the federation
 - integration with omnibolt/tether to allow day-trading and other "bad behavior" that nevertheless prevents self-custody from success
 
ideally, a fedimint mobile app should operate just like an exchange mobile app

 - easily buy/sell (up to the amount others in the federation are willing to put up)
 - lose/recover creds
 - maintain dollar and bitcoin balances
 - dca support
 - easily withdraw dollars or bitcoin to digital cash platforms like paypal, venmo & cashapp

**Comment by elsirion** [comment]
This is the repo/org of the Fedimint open source protocol, so I'll only go into detail about the parts concerning it.

> * integration with venmo/paypal to easily pay and buy bitcoin from the federation

Fedimint is an open, decentralized protocol and as such will not integrate with proprietary, centralized service providers, that's just out of scope for the Fedimint project. If people really want these integrations someone can build them independently or as extensions to the core protocol. E.g. a 3rd party-run paypal-LN bridge could be integrated with any federation without requiring any changes to the protocol.

> * integration with omnibolt/tether to allow day-trading and other "bad behavior" that nevertheless prevents self-custody from success

USD hedging is something I want to investigate since it is unfortunately still a much-needed feature due to Bitcoin's volatility that not everyone can absorb. The focus would be on allowing people to hold both a USD and a BTC balance and not trading though. Technological choices will be discussed and made when we come to that point depending on the available protocols at that time.

> ideally, a fedimint mobile app should operate just like an exchange mobile app

That's very much up to the integrators (i.e. people building wallet apps). Fedimint strives to provide a federated e-cash system with Lightning integration. Everything beyond that is currently out of scope. The software is built in a modular fashion, so if someone wanted to add some sort of exchange they could do so relatively easily (currently requires forking this repo, will hopefully be solved soonish, see #144).

On-boarding is a very location-dependent problem, so I don't think it can be solved to a satisfying degree by a protocol that's meant to be viable globally. Different communities will come up with different solutions. Some of them may be implemented as an extension to Fedimint eventually, some will be completely independent.

I hope this addresses your questions, feel free to reopen/comment otherwise :)
