### ISSUE TITLE
"FinalizationError(UnknownIssuance)" on fetch

### ISSUE THREAD

**Issue by NicolaLS** [fedimint/minimint#71]
When I tested spend + reissue I encountered "FinalizationError(UnknownIssuance)", and then it worked again without restarting (federations, clientd) or changing anything. The reissue status was Accepted though : 
![cli](https://user-images.githubusercontent.com/90551797/164605753-01876d56-e6dc-4041-9e55-bf1fd6898574.png)
![events](https://user-images.githubusercontent.com/90551797/164605771-4f102e98-75e6-4ad2-a07c-b6fb848b7f15.png)

**Comment by NicolaLS** [comment]
https://github.com/fedimint/minimint/blob/19fcfdbff4b30fa068c54237f995cf7c729f50f9/mint-client/src/mint/mod.rs#L177-L185

**Comment by NicolaLS** [comment]
I just noticed this happens a lot for me just hadn't noticed it

**Comment by elsirion** [comment]
I think no one was using the bare `fetch_coins` fn so far, so it not having retry logic went unnoticed:

https://github.com/fedimint/minimint/blob/19fcfdbff4b30fa068c54237f995cf7c729f50f9/mint-client/src/clients/user.rs#L269-L276

Ideally (in the short term) there'd probably be something like this

https://github.com/fedimint/minimint/blob/19fcfdbff4b30fa068c54237f995cf7c729f50f9/mint-client/src/mint/mod.rs#L234-L247

Later on I'd like to build long polling or some other form of notification system without polling.

**Comment by NicolaLS** [comment]
I don't use the bare fetch_coins() (in clientd::fetch) the problem was that I was getting a non-retry-able error when I should get a retry-able one. (I was confused and didn't explained that thought). I think I found a simple solution, by just swaping the order of https://github.com/fedimint/minimint/blob/de567ba89b4fd015bee9a2596ebbf00f55bc1c62/mint-client/src/mint/mod.rs#L178-L185 and https://github.com/fedimint/minimint/blob/de567ba89b4fd015bee9a2596ebbf00f55bc1c62/mint-client/src/mint/mod.rs#L187-L192 but now I always get errors like this :
![errors](https://user-images.githubusercontent.com/90551797/165493012-58f00aaf-0c3c-4a19-b96a-45cee9e81a42.png)

**Comment by NicolaLS** [comment]
(the problem is that when the bsig is not ready the 'let issuance = ...' returnes UnknownIssuance)

**Comment by elsirion** [comment]
Oh right, I got confused. When you read the error description of `UnknownIssuance` it says that the client doesn't know the issuance, so even if it existed in the federation it couldn't retrieve the coins. Swapping things around doesn't really fix anything imo? Why it looks like success: in the worst case it now fails with a retryable error all the time and sends you into an infinite loop that way if the issucance actually doesn't exist, in the best case you get a response but can't finalize it because it doesn't exist in the DB.

**Comment by NicolaLS** [comment]
In my case it worked but that's right this is no solution since in not my specific case that  would end in an endless loop.
The Error occurred  when I would 'spam' this script (if I call it then wait a few sec then call it again its all good) : 
`TOKENS=$(curl -X POST localhost:8081/rpc -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method": "spend","params": 100000000,"id": 1}' | jq '.result.Spend.token')
curl -X POST localhost:8081/rpc -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0","method": "reissue_validate","params": '"$TOKENS"',"id": 1}' | jq '.'`
The the important method here is reissue_validate : https://github.com/NicolaLS/minimint/blob/fd98ea2da74aacf7368dc998c95abb157aeb2fec/mint-client/src/bin/clientd/main.rs#L306-L331
it just waits for the federation to 'Accept' the coins and then fetches BUT when the coins are 'Accepted' there is **no sign response imediatley** which caused the error because my fetch_tx_outcome looks like this : https://github.com/NicolaLS/minimint/blob/fd98ea2da74aacf7368dc998c95abb157aeb2fec/mint-client/src/clients/user.rs#L391-L410 I changed it to also wait for the sign response but that made reissue_validate take much longer (but it solved the error). See the diff from first pic and this one :
![accpted](https://user-images.githubusercontent.com/90551797/165624574-8175b8a9-edf6-4d6a-a5ca-476cc20aa131.png)

**Comment by NicolaLS** [comment]
My first idea would be to put additional logic in the .ok_or(...) in fetch_coins to either return a OutputNotReadyYet OR an FinalizationError. Will try to implement now and link it later

**Comment by NicolaLS** [comment]
Would this be a solution ? 
https://github.com/NicolaLS/minimint/commit/5ed1948a17a3e582b3d23169a1f99fbff98de063

**Comment by elsirion** [comment]
Ah, now I understand what's happening: the client isn't really safe when run in parallel. Easiest fix would be putting the client into a Mutex (ideally a tokio one imo). When you run `fetch_all_coins` in parallel it first queries a list of all ongoing issuances but then queries each issuance a second time later on. If it was processed and removed in another thread in the meantime that gives you this error. 

The blocking with a Mutex would make the client slow. If a fetch is ongoing no other requests would be processed. An alternative would be to only introduce more fine grained locks for different operations:

* fetch: allow only 1 (have one thread running all the time for fetching)
* receive: infinitely many
* send: allow only 1

I think we could use a bunch of `Mutex<()>` for this.

For a better solution I'd like to wait for a fix to #25 since that will allow database transactions hopefully sidestepping the whole problem.

**Comment by NicolaLS** [comment]
Are the two most recent commits in #55 sufficient ?
